-- Run in WKSP_GCODE2 SQL Workshop (ATHARVA connection has no CREATE privilege there).
-- Verified against live schema 2026-07-31: EVENTS.ID is the real event PK (not GCODE_EVENTS,
-- which is a decoy - see memory db_schema_wksp_gcode2.md). GCODE_EVENT_PARTICIPANTS is real.

CREATE TABLE GCODE_COUPONS (
  ID               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EVENT_ID         NUMBER NOT NULL REFERENCES EVENTS(ID),
  CODE             VARCHAR2(30) NOT NULL,
  DISCOUNT_TYPE    VARCHAR2(10) NOT NULL,
  DISCOUNT_VALUE   NUMBER(10,2) NOT NULL,
  MAX_REDEMPTIONS  NUMBER,
  REDEMPTION_COUNT NUMBER DEFAULT 0 NOT NULL,
  VALID_FROM       TIMESTAMP,
  VALID_TO         TIMESTAMP,
  IS_ACTIVE        NUMBER(1) DEFAULT 1 NOT NULL,
  CREATED_BY       NUMBER,
  CREATED_ON       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UQ_GCODE_COUPONS_EVENT_CODE UNIQUE (EVENT_ID, CODE),
  CONSTRAINT CK_GCODE_COUPONS_TYPE CHECK (DISCOUNT_TYPE IN ('PERCENT','FIXED')),
  CONSTRAINT CK_GCODE_COUPONS_VALUE CHECK (DISCOUNT_VALUE > 0),
  CONSTRAINT CK_GCODE_COUPONS_PERCENT CHECK (DISCOUNT_TYPE != 'PERCENT' OR DISCOUNT_VALUE <= 100),
  CONSTRAINT CK_GCODE_COUPONS_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);

CREATE TABLE GCODE_COUPON_REDEMPTIONS (
  ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COUPON_ID   NUMBER NOT NULL REFERENCES GCODE_COUPONS(ID),
  EMAIL       VARCHAR2(255) NOT NULL,
  ORDER_ID    VARCHAR2(64),
  REDEEMED_ON TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UQ_GCODE_COUPON_REDEMPTIONS_EMAIL UNIQUE (COUPON_ID, EMAIL)
);

CREATE TABLE GCODE_UPI_PAYMENT_CLAIMS (
  ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EVENT_ID       NUMBER NOT NULL REFERENCES EVENTS(ID),
  EMAIL          VARCHAR2(255) NOT NULL,
  FULL_NAME      VARCHAR2(255) NOT NULL,
  UTR            VARCHAR2(30) NOT NULL,
  AMOUNT_CLAIMED NUMBER(10,2) NOT NULL,
  STATUS         VARCHAR2(10) DEFAULT 'PENDING' NOT NULL,
  SUBMITTED_ON   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  REVIEWED_BY    NUMBER,
  REVIEWED_ON    TIMESTAMP,
  PARTICIPANT_ID NUMBER REFERENCES GCODE_EVENT_PARTICIPANTS(ID),
  CONSTRAINT UQ_GCODE_UPI_CLAIMS_UTR UNIQUE (EVENT_ID, UTR),
  CONSTRAINT CK_GCODE_UPI_CLAIMS_STATUS CHECK (STATUS IN ('PENDING','CONFIRMED','REJECTED'))
);

CREATE INDEX IX_GCODE_COUPONS_EVENT ON GCODE_COUPONS(EVENT_ID);
CREATE INDEX IX_GCODE_COUPON_REDEMPTIONS_COUPON ON GCODE_COUPON_REDEMPTIONS(COUPON_ID);
CREATE INDEX IX_GCODE_UPI_CLAIMS_EVENT ON GCODE_UPI_PAYMENT_CLAIMS(EVENT_ID);
